
- name: Configurar servicios básicos
  hosts: containers
  become: yes
  tasks:
    - name: Instalar herramientas básicas
      apt:
        name: [git, curl]
        state: present
        update_cache: yes
